variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 16

stages:
  - build_up
  - ut_up
  - build_mp
  - ut_mp

before_script:
    - export PATH="$PATH:/home/vivoadmin/.cargo/bin"
    - rustup toolchain link mygnutoolchain "/home/vivoadmin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu"
    - rustup default mygnutoolchain
    
up-build:
  stage: build_up
  script:
    - echo "...开始NP构建..."  
    - cp bsp/qemu-vexpress-a9/.config_up bsp/qemu-vexpress-a9/rtconfig.h
    - ls -l bsp/qemu-vexpress-a9/rtconfig.h
    - ./build.sh qemu-vexpress-a9
  tags:
    - ubuntu
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  artifacts:
        name: "rtthread.bin"
        untracked: false
        expire_in: 5 mins
        paths:
            - /data01/runner/gitlab-runner/builds/y1GSVydi/0/11154271/rt-thread/bsp/qemu-vexpress-a9/rtthread.bin


up-unit-test:
  stage: ut_up
  dependencies:
    - up-build
  script:
    - echo "...测试NP代码..."  
    - cd bsp/qemu-vexpress-a9
    - timeout 90s ./qemu-test.sh || true
    - cd ../../
    - python check_result.py
  tags:
    - ubuntu
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    
mp-build:
  stage: build_mp
  script:
    - echo "...开始MP构建..."  
    - cp bsp/qemu-vexpress-a9/.config_mp bsp/qemu-vexpress-a9/rtconfig.h
    - ./build.sh qemu-vexpress-a9
  tags:
    - ubuntu
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  artifacts:
        name: "rtthread.bin"
        untracked: false
        expire_in: 5 mins
        paths:
            - /data01/runner/gitlab-runner/builds/y1GSVydi/0/11154271/rt-thread/bsp/qemu-vexpress-a9/rtthread.bin    

mp-unit-test:
  stage: ut_mp
  dependencies:
    - mp-build
  script:
    - echo "...测试MP代码..."  
    - cd bsp/qemu-vexpress-a9
    - timeout 90s ./qemu-test.sh || true
    - cd ../../
    - python check_result.py
  tags:
    - ubuntu
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

