header: # `header` section is configurations for source codes license header.
  - paths:
     - '**'
    license:
      spdx-id: Apache-2.0 # the spdx id of the license, it's convenient when your license is standard SPDX license.
      copyright-owner: vivo Mobile Communication Co., Ltd # the copyright owner to replace the [owner] in the `spdx-id` template.
      content:
        | # `license` will be used as the content when `fix` command needs to insert a license header.
        Copyright (c) 2025 vivo Mobile Communication Co., Ltd.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

              http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
      # `pattern` is optional regexp if all the file headers are the same as `license` or the license of `spdx-id` and `copyright-owner`.
      pattern: |
        Copyright (c) 2025 vivo Mobile Communication Co., Ltd.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

              http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

    paths-ignore: # `paths-ignore` are the path list that will be ignored by license-eye.
      - "licenses"
      - "**/cov.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/rust-toolchain.toml"
      - "**/rustfmt.toml"
      - "**/TODO"
      - "backup/**"
      - "kconfig/**/defconfig"
      - "LICENSES/**"
      - "CREDITS/**"
      - "kernel/src/allocator/buddy/**/*.rs" # special process for kernel imported
      - "kernel/src/allocator/llff/**/*.rs" # special process for kernel imported
      - "kernel/src/allocator/tlsf/**/*.rs" # special process for kernel imported
      - "kernel/src/sync/libatomic/**" # special process for kernel imported
      - "loader/tests/integration_test/src/test.rs"
      - "loader/tests/cov/lib.rs"
      - "adapter/rt_thread/include/rt_thread_wrapper.inc"
      - "kernel/src/sync/futex.rs"
      - "scal/src/platform/**"
      - ".gitignore"
      - "**/*.md"
      - "**/*.x" # ld link script
      - "**/*.bak"
      - "**/.config"
      - "**/Kconfig"
      - "**/LICENSE_*"
      - "**/common_checker.test" # qemu checker
      - "**/*.checker"
      - "LICENSE"
      - "NOTICE"
      - "**/bin"
      - "**/*.publickey"
      - ".licenserc.yaml"
      - "**/*.lds"
      - "**/lib64"
      - "adapter/cmsis_header/**" # CMSIS header files from third party

    comment: on-failure # on what condition license-eye will comment on the pull request, `on-failure`, `always`, `never`.

    # license-location-threshold specifies the index threshold where the license header can be located,
    # after all, a "header" cannot be TOO far from the file start.
    license-location-threshold: 75

    language:
      Rust:
        extensions:
          - ".rs"
          - ".rs.in"
        comment_style_id: DoubleSlash
      GN:
        extensions:
          - ".gn"
          - ".gni"
        comment_style_id: PythonStyle
      C++:
        extensions:
          - ".cpp"
          - ".h"
          - ".c"
          - ".cc"
          - ".hpp"
        comment_style_id: SlashAsterisk

