[workspace]

members = [
    "kernel",
    "arch",
    "adapter",
    "infra",
    "kconfig",
]

[patch.crates-io]

[profile.release]
codegen-units = 1 # better optimizations
debug = 1 # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
opt-level = "z"
