from building import *
import os

src = Glob('*.c')
cwd = GetCurrentDir()

libs = ["rtcore"]
libpath = [cwd + "/target/armv7a-none-eabi/debug"]
group = DefineGroup('Rust', src, depend = [''], CPPPATH = [], LIBS=libs, LIBPATH=libpath, CPPDEFINES = ['__RTTHREAD__'])

Return('group')