# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    scons_file = os.path.join(path, 'SConscript')
    if os.path.isfile(scons_file):
        objs = objs + SConscript(scons_file)

Return('objs')
