from building import *
import os

src = Glob('*.c')
cwd = GetCurrentDir()

libs = ["adapter"]
libpath = [cwd + "/target"]
group = DefineGroup('Rust', src, depend = ['USE_RUST'], CPPPATH = [], LIBS=libs, LIBPATH=libpath, CPPDEFINES = ['__RTTHREAD__'])

Return('group')